Repository Group4project1/project1, pull requests merged in 2020-06, with the labels that each got.

#14 Adding question
  Assets/css/style.css
  Assets/script/script.js
  index.html
Labels: MVP

#15 update readMe
  Assets/Images/homepage.png
  README.md
Labels: MVP

#19 17 localstorage
  Assets/script/script.js
  index.html
Labels: MVP

#20 Added API Logic to Populate Cards
  Assets/css/style.css
  Assets/script/script.js
  index.html
Labels: MVP

#23 Added APIs and Alternative Recs Path
  Assets/Images/successful.png
  Assets/Images/unsuccessful.png
  Assets/css/style.css
  Assets/script/script.js
  index.html
Labels: MVP

#26 including Antonio's edits and additional function
  Assets/script/script.js
Labels: bug

#28 Added Team Bios
  Assets/Images/juliet.jpg
  Assets/Images/krystal.jpg
  Assets/Images/vandolph.jpg
  Assets/css/style.css
  bios.html
  index.html
Labels: enhancement

#30 Fixed Responsive UI Layout
  Assets/css/style.css
  Assets/script/script.js
  bios.html
  index.html
Labels: MVP
